---
- name: Display Results Report
  hosts: webservers
  become: true

  tasks:
  - name: Moving Report file
    copy:
      src: /openscap/{{ profile }}_report.html
      dest: /var/www/html/{{ profile }}.html
      owner: apache
      mode: "664"
   
  - name: Restart Apache
    service:
      name: httpd
      state: restarted
