---
- name: OpenSCAP Install & Scanning
  hosts: webservers
  become: true

  tasks:
  - name: Installing OpenSCAP Scanner
    yum:
      name: openscap-scanner
      state: latest

  - name: Install OpenSCAP Security Guide
    yum: 
      name: scap-security-guide
      state: latest

  - name: Download the latest RHSA OVAL definitions 
    get_url:
      url: https://www.redhat.com/security/data/oval/v2/RHEL8/rhel-8.oval.xml.bz2
      dest: /tmp/rhel-8.oval.xml.bz2
      mode: 644
  
  - name: Decompress OVAL definitions
    command:
      cmd: bzip2 --decompress /tmp/rhel-8.oval.xml.bz2 > /tmp/rhel-8.oval.xml
 
  - name: Scan System and save results to vulnerabilities.html
    command:
      cmd: oscap oval eval --report /tmp/vulnerability.html /tmp/rhel-8.oval.xml
