---
- name: OpenSCAP Install & Scanning
  hosts: webservers
  become: true

  tasks:
  - name: Installing OpenSCAP Scanner
    yum:
      name: openscap-scanner
      state: latest

  - name: Install OpenSCAP Security Guide
    yum: 
      name: scap-security-guide
      state: latest
  
  - name: Get timestamp
    command: date +%Y%m%d%T
    register: timestamp

  - name: Create OpenSCAP Directory
    file:
      path: /openscap
      state: directory
      mode: "775"

  - name: Scan System Against DISA STIG and generate Report
    command:
      cmd: oscap xccdf eval --results /openscap/rhel8-stig-results-{{ timestamp.stdout }}.xml --report /openscap/{{ profile }}_report.html --profile {{ profile }} /usr/share/xml/scap/ssg/content/ssg-rhel8-ds.xml
    ignore_errors: true
 
  - name: Generate remediation Playbook
    command:
      cmd: oscap xccdf generate fix --fix-type {{ fix_type }} --profile {{ profile }} --output /openscap/rhel8-stig-remediations{{ timestamp.stdout }}.yml /openscap/rhel8-stig-results-{{ timestamp.stdout }}.xml
