---
- name: Upgrading Packages
  hosts: webservers
  become: true
  gather_facts: false

  tasks:
  - name: Upgrade Packages
    dnf:
      name: '*'
      state: latest
      update_cache: yes
      update_only: no
    register: reg_dnf_output_upgrade

  - name: List Packages 
    debug:
      msg: "{{ reg_dnf_output_upgrade.results | map(attribute='name') | list }}"

  - name: Patch Packages
    dnf:
      name: '*'
      security: yes
      state: latest
      update_cache: yes
      update_only: no
    register: reg_dnf_output_security

  - name: List Security Packages
    debug:
      msg: "{{ reg_dnf_output_security.results | map(attribute='name') | list }}"
