---
- name: Upgrading Packages
  hosts: webservers
  become: true
  gather_facts: false

  tasks:
  - name: Upgrade Packages
    dnf:
      name: '*'
      state: latest
      update_cache: yes
      update_only: no
    register: reg_dnf_output_upgrade

  - name: List Packages 
    debug:
      msg: "{{ reg_dnf_output_upgrade.results | list }}"
