---
- name: Patch Packages
  hosts: webservers
  become: true
  gather_facts: false

  tasks:
  - name: Patch Package (Security)
    dnf:
      name: '*'
      security: yes
      state: latest
      update_cache: yes
      update_only: no
    register: reg_dnf_output_security

  - name: List Security Packages
    debug:
      msg: "{{ reg_dnf_output_security.results | list }}"
